[global]
   workgroup = WORKGROUP
   server string = Servidor Samba Homelab
   netbios name = SERVIDORLINUX
   security = user
   map to guest = Bad User
   dns proxy = no

[publico]
   comment = Compartilhamento Publico Homelab
   path = /samba/publico
   browseable = yes
   read only = no
   guest ok = no
   valid users = suporte
   force create mode = 0777
   force directory mode = 0777
